[package]
name = "wasm4-game-jam"
version = "0.1.0"
edition = "2021"
authors = ["Max Curzi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
