[package]
name = "maxcurzi/disk-0-MADNESS"
version = "1.1.0"
description = "A bullet hell where you absorb bullets to score. Now with multiplayer co-op!"
license = "ISC"
readme = "README.md"
repository = "https://github.com/maxcurzi/disk-0-madness"

[dependencies]
"maxcurzi/disk-0-MADNESS" = "1.1.0"

[[module]]
name = "disk-0-madness"
source = "disk-0-madness.wasm"
abi = "wasm4"

[module.interfaces]
wasm4 = "0.0.1"

[[command]]
name = "play"
module = "disk-0-madness"
